# Generated by Django 3.2.7 on 2021-10-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211002_0131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpadate',
            new_name='OrderUpdate',
        ),
    ]
