# Generated by Django 3.2.7 on 2021-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_orderupadate_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
