# Generated by Django 3.2.7 on 2021-10-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211016_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_id',
        ),
        migrations.DeleteModel(
            name='ManageAddress',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
