# Generated by Django 3.2.7 on 2021-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211016_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='productsName',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
