# Generated by Django 3.2.7 on 2021-10-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211016_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=254)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.register')),
            ],
        ),
    ]
