# Generated by Django 3.2.7 on 2021-10-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
