# Generated by Django 3.2.7 on 2021-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_id',
        ),
    ]
