# Generated by Django 3.2.7 on 2021-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_user_register_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='securityAnswer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='securityQuestion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
